language: erlang
script: "make"
notifications:
  email: false
before_install:
  - sudo apt-get update
  - sudo apt-get -y install check cmake
otp_release:
  - 22.3
  - 23.3
  - 24.3
  - 25.3
  - 26.2
  - 27.2
